[package]
name = "vennbase"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21.4"
logic-parser = "1.2.0"

[dependencies.chrono]
version = "0.4.31"
features = ["alloc", "std", "clock"]

[dependencies.uuid]
version = "1.4.1"
features = ["v4", "fast-rng", "macro-diagnostics"]
